- name: mysql data
  hosts: localhost
  become: yes 
  tasks:
  - name: disable the mysql
    ansible.builtin.shell:
      dnf module disable mysql -y
  - name: copy the mysql repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-community-server
      state: present
  - name: start and enable mysqld
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1