- name: Install web component on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Remove html directory
      ansible.builtin.file:
        path: /var/www/html
        state: absent

    - name: Create html directory
      ansible.builtin.file:
        path: /var/www/html
        state: present

    - name: Download web app
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /usr/share/nginx/html
        validate_certs: no
          
    - name: Extract application
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /var/www/html
        remote_src: yes

    - name: Copy roboshop configuration
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/sites-available/roboshop.conf

    - name: Enable roboshop configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/roboshop.conf
        dest: /etc/nginx/sites-enabled/roboshop.conf
        state: link

    - name: Remove default Nginx config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    #- name: Test Nginx configuration
     # ansible.builtin.command: nginx -t

    - name: Restart and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
